general:
#  driver_path: edge-driver/msedgedriver.exe
  driver_path: edge-driver/msedgedriver
  page_loading_time: 3
  action_wait_time: 1
  rate_limit_wait_time: 30
  headless: yes  # yes or no - if yes, the browser will not be displayed
  mode: roundtrip  # oneway or roundtrip

account:
  username: ""
  password: ""
  wizzair_url: "https://multipass.wizzair.com/de/w6/subscriptions"


flight_data:
  max_stops: 0  # 0 or 1
  departure_date:
  return_date:
  destination_airports:   # If not specified, all possible destination airports will be checked
    - London Luton (LTN)
    - Budapest (BUD)
    - Kopenhagen (CPH)
    - Madrid (MAD)

  departure_airports:
    - Riad
    - Barcelona El Prat
    - Amman
    - Abu Dhabi
    - Memmingen/München-West


logging_config:
  dictConfig:
    version: 1
    disable_existing_loggers: false

    formatters:
      modulePathFormatter:
        '()': logging_utils.ModulePathFormatter
        format: "%(asctime)s - %(levelname)s - [%(module_path)s:%(lineno)d in %(funcName)s()] %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"

    handlers:
      console_handler:
        class: logging.StreamHandler
        level: INFO  # or use the same as log_level_console
        formatter: modulePathFormatter
        stream: ext://sys.stdout

      file_handler:
        class: logging.FileHandler
        level: INFO  # or use the same as log_level_console
        formatter: modulePathFormatter
        filename: "wizzair-scraper.log"
        mode: w
        encoding: utf-8

      file_handler_debug:
        class: logging.FileHandler
        level: DEBUG  # matches log_level_file
        formatter: modulePathFormatter
        # If you want wizzair-scraper-debug.log specifically:
        filename: "wizzair-scraper-debug.log"
        mode: w
        encoding: utf-8

    root:
      level: DEBUG
      handlers: [console_handler, file_handler, file_handler_debug]


data_manager:
  airport_iata_icao_path: data/airport_iata_icao_filtered.csv
  flight_data_path: data/flight_data.yaml
  airport_name_special_cases_path: data/airport_name_special_cases.yaml
  airport_database_iata_path: data/airport_database_iata.yaml
  map_iata_to_german_name_path: data/map_iata_to_german_name.yaml
  airport_database_path: data/airport_database.yaml
  possible_flights_path: data/possible_flights.yaml
  checked_flights_path: data/checked_flights.yaml
  available_flights_path: data/available_flights.yaml
  use_cache: yes  # yes or no - if yes data in the database will not be scraped again

reporter:
  report_path: data/report.pdf
  logo_path: data/logo.png

scraper:
  initialize_driver: yes  # yes or no - if no, the driver will not be initialized


emailer:
  recipient: test