[theme]
primaryColor = "#C90076"              # Vivid magenta – matches banner left
backgroundColor = "#FFF8FC"           # Soft blush – clean, inviting
secondaryBackgroundColor = "#F4E8FF"  # Pale lavender – from banner right
textColor = "#2D0039"                 # Deep plum – readable, elegant
#font = "sans serif"
